// products.js — Auto parts catalog data
// Currency: Malaysian Ringgit (RM)
// Each product is categorised by car BRAND and includes a gallery of images,
// price, and direct links to Shopee and TikTok Shop.

const BRANDS = [
  "Toyota", "Mazda", "Isuzu", "Honda", "Mitsubishi",
  "Nissan", "Suzuki", "Chevrolet", "Hino"
];

const IMG = "images/";

const products = [
  {
    id: 1,
    name: "Toyota Ceramic Brake Pads (Front)",
    brand: "Toyota",
    part: "Brake Pads",
    price: 129.90,
    sku: "TY-BP-001",
    stock: 24,
    description: "Low-dust ceramic front brake pads engineered for Toyota models. Quiet operation, consistent stopping power and longer rotor life.",
    specs: { Position: "Front axle", Material: "Ceramic", Warranty: "12 months", Fitment: "Vios, Altis, Camry" },
    images: [IMG + "brake-pads.jpg", IMG + "brake-disc.jpg", IMG + "packaging.jpg"],
    shopee: "https://shopee.com.my/autoparts/toyota-brake-pads",
    tiktok: "https://www.tiktok.com/@autoparts/toyota-brake-pads"
  },
  {
    id: 2,
    name: "Toyota Premium Oil Filter",
    brand: "Toyota",
    part: "Oil Filter",
    price: 24.50,
    sku: "TY-OF-002",
    stock: 80,
    description: "OEM-grade spin-on oil filter with high filtration efficiency to protect your Toyota engine between services.",
    specs: { Type: "Spin-on", Thread: "M20 x 1.5", Warranty: "6 months", Fitment: "Most Toyota petrol engines" },
    images: [IMG + "oil-filter.jpg", IMG + "packaging.jpg"],
    shopee: "https://shopee.com.my/autoparts/toyota-oil-filter",
    tiktok: "https://www.tiktok.com/@autoparts/toyota-oil-filter"
  },
  {
    id: 3,
    name: "Toyota LED Headlight Assembly",
    brand: "Toyota",
    part: "Headlight",
    price: 459.00,
    sku: "TY-HL-003",
    stock: 10,
    description: "Plug-and-play LED projector headlight assembly with bright, even beam pattern and modern styling.",
    specs: { Bulb: "Built-in LED", Side: "Driver / Passenger", Warranty: "12 months", Fitment: "Hilux, Fortuner" },
    images: [IMG + "headlight.jpg", IMG + "packaging.jpg"],
    shopee: "https://shopee.com.my/autoparts/toyota-headlight",
    tiktok: "https://www.tiktok.com/@autoparts/toyota-headlight"
  },
  {
    id: 4,
    name: "Mazda Engine Air Filter",
    brand: "Mazda",
    part: "Air Filter",
    price: 35.90,
    sku: "MZ-AF-004",
    stock: 60,
    description: "High-flow pleated air filter that keeps dust and debris out while maximising airflow for SkyActiv engines.",
    specs: { Type: "Panel", Material: "Pleated paper", Warranty: "6 months", Fitment: "Mazda 3, CX-5" },
    images: [IMG + "air-filter.jpg", IMG + "packaging.jpg"],
    shopee: "https://shopee.com.my/autoparts/mazda-air-filter",
    tiktok: "https://www.tiktok.com/@autoparts/mazda-air-filter"
  },
  {
    id: 5,
    name: "Mazda Iridium Spark Plugs (Set of 4)",
    brand: "Mazda",
    part: "Spark Plugs",
    price: 119.00,
    sku: "MZ-SP-005",
    stock: 40,
    description: "Iridium spark plugs for smoother starts, better fuel economy and reliable ignition. Sold as a set of four.",
    specs: { Quantity: "4 pcs", Electrode: "Iridium", Warranty: "12 months", Fitment: "Mazda 2, 3, 6" },
    images: [IMG + "spark-plugs.jpg", IMG + "packaging.jpg"],
    shopee: "https://shopee.com.my/autoparts/mazda-spark-plugs",
    tiktok: "https://www.tiktok.com/@autoparts/mazda-spark-plugs"
  },
  {
    id: 6,
    name: "Isuzu Aluminium Radiator",
    brand: "Isuzu",
    part: "Radiator",
    price: 389.00,
    sku: "IZ-RD-006",
    stock: 8,
    description: "Heavy-duty aluminium radiator with high cooling capacity, ideal for Isuzu pickups and commercial use.",
    specs: { Core: "Aluminium", Rows: "2", Warranty: "12 months", Fitment: "D-Max, MU-X" },
    images: [IMG + "radiator.jpg", IMG + "packaging.jpg"],
    shopee: "https://shopee.com.my/autoparts/isuzu-radiator",
    tiktok: "https://www.tiktok.com/@autoparts/isuzu-radiator"
  },
  {
    id: 7,
    name: "Isuzu Heavy-Duty Clutch Kit",
    brand: "Isuzu",
    part: "Clutch Kit",
    price: 649.00,
    sku: "IZ-CK-007",
    stock: 6,
    description: "Complete clutch kit including disc, pressure plate and release bearing for dependable power transfer.",
    specs: { Includes: "Disc, plate, bearing", Diameter: "240 mm", Warranty: "12 months", Fitment: "D-Max 2.5/3.0" },
    images: [IMG + "clutch-kit.jpg", IMG + "packaging.jpg"],
    shopee: "https://shopee.com.my/autoparts/isuzu-clutch-kit",
    tiktok: "https://www.tiktok.com/@autoparts/isuzu-clutch-kit"
  },
  {
    id: 8,
    name: "Honda Ceramic Brake Pads (Front)",
    brand: "Honda",
    part: "Brake Pads",
    price: 119.90,
    sku: "HD-BP-008",
    stock: 30,
    description: "Premium ceramic front brake pads for Honda models, offering quiet braking and minimal brake dust.",
    specs: { Position: "Front axle", Material: "Ceramic", Warranty: "12 months", Fitment: "City, Civic, CR-V" },
    images: [IMG + "brake-pads.jpg", IMG + "brake-disc.jpg", IMG + "packaging.jpg"],
    shopee: "https://shopee.com.my/autoparts/honda-brake-pads",
    tiktok: "https://www.tiktok.com/@autoparts/honda-brake-pads"
  },
  {
    id: 9,
    name: "Honda Alternator 12V 90A",
    brand: "Honda",
    part: "Alternator",
    price: 529.00,
    sku: "HD-AL-009",
    stock: 7,
    description: "Reconditioned-to-OEM-spec alternator delivering stable charging for Honda's electrical system.",
    specs: { Voltage: "12V", Output: "90A", Warranty: "12 months", Fitment: "City, Jazz, Civic" },
    images: [IMG + "alternator.jpg", IMG + "packaging.jpg"],
    shopee: "https://shopee.com.my/autoparts/honda-alternator",
    tiktok: "https://www.tiktok.com/@autoparts/honda-alternator"
  },
  {
    id: 10,
    name: "Honda Engine Air Filter",
    brand: "Honda",
    part: "Air Filter",
    price: 32.90,
    sku: "HD-AF-010",
    stock: 70,
    description: "Direct-fit air filter that protects your Honda engine and restores throttle response.",
    specs: { Type: "Panel", Material: "Pleated paper", Warranty: "6 months", Fitment: "City, Civic, HR-V" },
    images: [IMG + "air-filter.jpg", IMG + "packaging.jpg"],
    shopee: "https://shopee.com.my/autoparts/honda-air-filter",
    tiktok: "https://www.tiktok.com/@autoparts/honda-air-filter"
  },
  {
    id: 11,
    name: "Mitsubishi Gas Shock Absorber (Rear)",
    brand: "Mitsubishi",
    part: "Shock Absorber",
    price: 179.00,
    sku: "MT-SA-011",
    stock: 18,
    description: "Gas-charged rear shock absorber for a controlled, comfortable ride and improved stability.",
    specs: { Position: "Rear", Type: "Gas-charged", Warranty: "12 months", Fitment: "Triton, ASX" },
    images: [IMG + "shock-absorber.jpg", IMG + "packaging.jpg"],
    shopee: "https://shopee.com.my/autoparts/mitsubishi-shock-absorber",
    tiktok: "https://www.tiktok.com/@autoparts/mitsubishi-shock-absorber"
  },
  {
    id: 12,
    name: "Mitsubishi Premium Oil Filter",
    brand: "Mitsubishi",
    part: "Oil Filter",
    price: 23.90,
    sku: "MT-OF-012",
    stock: 90,
    description: "Reliable spin-on oil filter keeping engine oil clean and your Mitsubishi running smoothly.",
    specs: { Type: "Spin-on", Thread: "M20 x 1.5", Warranty: "6 months", Fitment: "Triton, Xpander" },
    images: [IMG + "oil-filter.jpg", IMG + "packaging.jpg"],
    shopee: "https://shopee.com.my/autoparts/mitsubishi-oil-filter",
    tiktok: "https://www.tiktok.com/@autoparts/mitsubishi-oil-filter"
  },
  {
    id: 13,
    name: "Nissan Iridium Spark Plugs (Set of 4)",
    brand: "Nissan",
    part: "Spark Plugs",
    price: 115.00,
    sku: "NS-SP-013",
    stock: 35,
    description: "Long-life iridium spark plugs for efficient combustion and dependable cold starts.",
    specs: { Quantity: "4 pcs", Electrode: "Iridium", Warranty: "12 months", Fitment: "Almera, X-Trail" },
    images: [IMG + "spark-plugs.jpg", IMG + "packaging.jpg"],
    shopee: "https://shopee.com.my/autoparts/nissan-spark-plugs",
    tiktok: "https://www.tiktok.com/@autoparts/nissan-spark-plugs"
  },
  {
    id: 14,
    name: "Nissan LED Headlight Assembly",
    brand: "Nissan",
    part: "Headlight",
    price: 439.00,
    sku: "NS-HL-014",
    stock: 9,
    description: "Modern LED headlight assembly with crisp output and easy plug-and-play installation.",
    specs: { Bulb: "Built-in LED", Side: "Driver / Passenger", Warranty: "12 months", Fitment: "Navara, X-Trail" },
    images: [IMG + "headlight.jpg", IMG + "packaging.jpg"],
    shopee: "https://shopee.com.my/autoparts/nissan-headlight",
    tiktok: "https://www.tiktok.com/@autoparts/nissan-headlight"
  },
  {
    id: 15,
    name: "Suzuki Engine Air Filter",
    brand: "Suzuki",
    part: "Air Filter",
    price: 29.90,
    sku: "SZ-AF-015",
    stock: 55,
    description: "High-flow air filter that keeps Suzuki engines breathing clean for better efficiency.",
    specs: { Type: "Panel", Material: "Pleated paper", Warranty: "6 months", Fitment: "Swift, Jimny" },
    images: [IMG + "air-filter.jpg", IMG + "packaging.jpg"],
    shopee: "https://shopee.com.my/autoparts/suzuki-air-filter",
    tiktok: "https://www.tiktok.com/@autoparts/suzuki-air-filter"
  },
  {
    id: 16,
    name: "Suzuki Ceramic Brake Pads (Front)",
    brand: "Suzuki",
    part: "Brake Pads",
    price: 99.90,
    sku: "SZ-BP-016",
    stock: 26,
    description: "Affordable ceramic front brake pads delivering smooth, quiet and reliable braking for Suzuki cars.",
    specs: { Position: "Front axle", Material: "Ceramic", Warranty: "12 months", Fitment: "Swift, Jimny" },
    images: [IMG + "brake-pads.jpg", IMG + "brake-disc.jpg", IMG + "packaging.jpg"],
    shopee: "https://shopee.com.my/autoparts/suzuki-brake-pads",
    tiktok: "https://www.tiktok.com/@autoparts/suzuki-brake-pads"
  },
  {
    id: 17,
    name: "Chevrolet Alternator 12V 100A",
    brand: "Chevrolet",
    part: "Alternator",
    price: 559.00,
    sku: "CV-AL-017",
    stock: 5,
    description: "High-output alternator built to OEM specification for steady charging in Chevrolet vehicles.",
    specs: { Voltage: "12V", Output: "100A", Warranty: "12 months", Fitment: "Colorado, Captiva" },
    images: [IMG + "alternator.jpg", IMG + "packaging.jpg"],
    shopee: "https://shopee.com.my/autoparts/chevrolet-alternator",
    tiktok: "https://www.tiktok.com/@autoparts/chevrolet-alternator"
  },
  {
    id: 18,
    name: "Chevrolet Aluminium Radiator",
    brand: "Chevrolet",
    part: "Radiator",
    price: 409.00,
    sku: "CV-RD-018",
    stock: 6,
    description: "Durable aluminium radiator with excellent heat dissipation for Chevrolet trucks and SUVs.",
    specs: { Core: "Aluminium", Rows: "2", Warranty: "12 months", Fitment: "Colorado, Trailblazer" },
    images: [IMG + "radiator.jpg", IMG + "packaging.jpg"],
    shopee: "https://shopee.com.my/autoparts/chevrolet-radiator",
    tiktok: "https://www.tiktok.com/@autoparts/chevrolet-radiator"
  },
  {
    id: 19,
    name: "Hino Heavy-Duty Clutch Kit",
    brand: "Hino",
    part: "Clutch Kit",
    price: 1290.00,
    sku: "HN-CK-019",
    stock: 4,
    description: "Commercial-grade clutch kit designed for the high torque demands of Hino trucks.",
    specs: { Includes: "Disc, plate, bearing", Diameter: "300 mm", Warranty: "12 months", Fitment: "Hino 300, 500 Series" },
    images: [IMG + "clutch-kit.jpg", IMG + "packaging.jpg"],
    shopee: "https://shopee.com.my/autoparts/hino-clutch-kit",
    tiktok: "https://www.tiktok.com/@autoparts/hino-clutch-kit"
  },
  {
    id: 20,
    name: "Hino Heavy-Duty Shock Absorber",
    brand: "Hino",
    part: "Shock Absorber",
    price: 299.00,
    sku: "HN-SA-020",
    stock: 12,
    description: "Robust shock absorber tuned for load-bearing stability and durability on Hino commercial vehicles.",
    specs: { Position: "Front / Rear", Type: "Gas-charged", Warranty: "12 months", Fitment: "Hino 300 Series" },
    images: [IMG + "shock-absorber.jpg", IMG + "packaging.jpg"],
    shopee: "https://shopee.com.my/autoparts/hino-shock-absorber",
    tiktok: "https://www.tiktok.com/@autoparts/hino-shock-absorber"
  }
];
